### ISSUE TITLE
Game Crash, when Ablator reaches Zero

### ISSUE THREAD

**Issue by fluff-y** [KSP-RO/DeadlyReentry#26]
Version 8.0.0, KSP 1.10.1

Depleting the ablator down to zero causes an instant Game crash. 
I noticed this happening repeatedly when reentering with the "ROC-ApolloCM" capsule attached to a heat shield. That capsule has for some reason 10 Units of ablator, which deplete very quickly even on a LEO-Reentry. 

The problem isn't specific to the capsule however, testing this with other parts resulted in the same way.
 
Removing the ModuleHeatShield on the Apollo capsule was a quick Band-aid fix, but the problem remains on other ablative parts.

[ModuleManager.ConfigCache.txt](https://github.com/KSP-RO/DeadlyReentry/files/6728918/ModuleManager.ConfigCache.txt)
[Player-prev.log](https://github.com/KSP-RO/DeadlyReentry/files/6728891/Player-prev.log)

Edit:
The issue is gone when downgrading back to Version 7.8.0.

**Comment by NathanKell** [comment]
You are getting log entries about onPartRepaired, i.e.

`MissingFieldException: Field 'GameEvents.onPartRepaired' not found.

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

That makes me think you have mod(s) incompatible with 1.10.

Can you also upload your ksp.log ? That shows all mods and their versions.

**Comment by fluff-y** [comment]
The exceptions "GameEvents.onPartRepaired" was caused by Restock, reverting back it back to 1.2.1 removed all of them.
I retested the original problem with Restock 1.2.1 & DeadlyReentry 8.0.0, the game is still crashing.

New Logs:
[Player.log](https://github.com/KSP-RO/DeadlyReentry/files/6732237/Player.log)
[KSP.log](https://github.com/KSP-RO/DeadlyReentry/files/6732244/KSP.log)
[ModuleManager.ConfigCache.txt](https://github.com/KSP-RO/DeadlyReentry/files/6732255/ModuleManager.ConfigCache.txt)

**Comment by NathanKell** [comment]
Could not reproduce. The end of your log file implies something went NaN, so I'm guessing something in some mod is dividing by ablator remaining.

I think what is actually causing your issue is that, prior to 8.0, heat shields had their max temps (and max skin temps) lowered to 0.85x, just like all other parts. In 8.0, their max temps are left alone. That means that in 8.0, once your shield's ablator depletes, it will take longer to explode from heat, giving (whatever is checking ablator) more time to actually do its check and blow up the world via NaNs.

I'm sorry to say this, but I suggest narrowing down to just essentials and then gradually building back up. Because there's an awful lot of stuff in there.

**Comment by NathanKell** [comment]
Actually, on depletion your shield's maxtemp lowers, just as it did in 7.x, but I still think it's probably due to that change? Before your shield might blow up earlier, and now it does not. That's the only thing I can think of that did change, and since I can't reproduce, I'm going to chalk it up to "some mod is calculating something regarding resource amounts, and did a divide-by-zero".

**Comment by fluff-y** [comment]
I will try removing mods and updating them to zero it down and come back to you later.
